{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "bb9af3b5-9756-44f1-b02a-6e02f69e7c87",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Your total ROI is 0.013997200559888023%\n"
     ]
    }
   ],
   "source": [
    "from IPython.display import clear_output\n",
    "\n",
    "class roi:\n",
    "    def __init__(self):\n",
    "        pass\n",
    "        \n",
    "    \n",
    "    def income(self):\n",
    "        \n",
    "        while True:\n",
    "            \n",
    "            try:\n",
    "                rentalincome = input(\"How much is your total rental income?\")\n",
    "\n",
    "                self.rentalincome = int(rentalincome)\n",
    "               \n",
    "                break\n",
    "                \n",
    "                \n",
    "                \n",
    "            except:\n",
    "\n",
    "                print('This is not a number, please type again!')\n",
    "                \n",
    "                \n",
    "                \n",
    "               \n",
    "        while True: \n",
    "            \n",
    "            try:\n",
    "                \n",
    "                otherincome= input(\"How much are your other total income?\")\n",
    "                \n",
    "                self.otherincome = int(otherincome)\n",
    "                \n",
    "                break\n",
    "                \n",
    "                \n",
    "            \n",
    "            except:\n",
    "\n",
    "                print('This is not a number, please type again!')\n",
    "                \n",
    "        self.totalincome = self.rentalincome + self.otherincome\n",
    "        \n",
    "        \n",
    "        clear_output()\n",
    "        \n",
    "    def expense(self):\n",
    "        \n",
    "        while True: \n",
    "            \n",
    "            try:\n",
    "                totaltax = input(\"How much is your total tax?\")\n",
    "                \n",
    "                self.totaltax = int(totaltax)\n",
    "                \n",
    "                break\n",
    "            \n",
    "            except:\n",
    "\n",
    "                print('This is not a number, please type again!')\n",
    "        \n",
    "        \n",
    "        while True:\n",
    "                \n",
    "            try:\n",
    "                \n",
    "                totalinsurance= input(\"how much is your total insurance?\")\n",
    "                \n",
    "                self.totalinsurance = int(totalinsurance)\n",
    "                \n",
    "                break\n",
    "                \n",
    "            except:\n",
    "\n",
    "                print('This is not a number, please type again!')\n",
    "                \n",
    "                \n",
    "        clear_output()\n",
    "        \n",
    "        while True:\n",
    "                \n",
    "            try:\n",
    "                \n",
    "                totalHOA = input(\"how much is your total HOA fees?\")\n",
    "                \n",
    "                self.totalHOA = int(totalHOA)\n",
    "                \n",
    "                break\n",
    "            \n",
    "            except:\n",
    "\n",
    "                print('This is not a number, please type again!')\n",
    "                \n",
    "                 \n",
    "                \n",
    "        while True:\n",
    "                \n",
    "            try:      \n",
    "                \n",
    "                totalmortage = input(\"how much is your total montly mortage?\")\n",
    "                \n",
    "                self.totalmortage = int(totalmortage)\n",
    "                \n",
    "                break\n",
    "                \n",
    "            except:\n",
    "\n",
    "                print('This is not a number, please type again!')\n",
    "                \n",
    "            \n",
    "           \n",
    "        while True:\n",
    "                \n",
    "            try:  \n",
    "                totalotherexpense = input(\"how much is your total other expenses?\") \n",
    "                \n",
    "                self.totalotherexpense = int(totalotherexpense)\n",
    "                \n",
    "                break\n",
    "                \n",
    "            except:\n",
    "                \n",
    "                print('This is not a number, please type again!')\n",
    "        \n",
    "        self.totalexpense = self.totaltax + self.totalinsurance + self.totalHOA + self.totalmortage + self.totalotherexpense\n",
    "        clear_output()\n",
    "        \n",
    "    def cashflow(self):\n",
    "\n",
    "        self.totalcashflow = self.totalincome - self.totalexpense\n",
    "\n",
    "        print(f'Your total cash flow is {self.totalcashflow}')\n",
    "        \n",
    "        clear_output()\n",
    "    def cashoncash(self):\n",
    "        \n",
    "        while True:\n",
    "            \n",
    "            try:\n",
    "        \n",
    "                totaldownpayment = input(\"How much is your down payment?\")\n",
    "\n",
    "                self.totaldownpayment = int(totaldownpayment)\n",
    "                \n",
    "                break\n",
    "            \n",
    "            except:\n",
    "                \n",
    "                print('This is not a number, please type again!')\n",
    "        \n",
    "                \n",
    "        while True:\n",
    "            \n",
    "            try:      \n",
    "                totalclosingcost = input(\"How much is your closing cost?\")\n",
    "                \n",
    "                self.totalclosingcost = int(totalclosingcost)\n",
    "                \n",
    "                break\n",
    "                \n",
    "            except:\n",
    "                \n",
    "                print('This is not a number, please type again!')\n",
    "                \n",
    "        while True:\n",
    "            \n",
    "            try:\n",
    "            \n",
    "                totalothercost = input(\"How much are you other total costs, such as rehabilitation cost, for example?\")\n",
    "                \n",
    "                self.totalothercost = int(totalothercost)\n",
    "                \n",
    "                break\n",
    "            \n",
    "            except:\n",
    "                \n",
    "                print('This is not a number, please type again!')\n",
    "        \n",
    "        \n",
    "        self.totalinvestment = self.totaldownpayment + self.totalclosingcost + self.totalothercost\n",
    "        \n",
    "        self.totalroi = (self.totalcashflow*2)/self.totalinvestment\n",
    "        \n",
    "        \n",
    "        \n",
    "        clear_output()\n",
    "        \n",
    "        print(f'Your total ROI is {self.totalroi}%')\n",
    "\n",
    "        \n",
    "house=roi()\n",
    "house.income()\n",
    "house.expense()\n",
    "house.cashflow()\n",
    "house.cashoncash()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "21680fe8-9c06-4edf-b9f6-f65d230ee4a7",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
